### ISSUE TITLE
Support for wiremock-rs expect

### ISSUE THREAD

**Issue by geovie** [beltram/stubr#426]
Hi, first thanks for providing this crate it has made it really easy to setup json stubs.

While integrating it with one of my project I noticed that there is no way to ensure that a request has been handled by the mock server.

Now wiremock-rs would support verifying that a request has been made via the [expect](https://docs.rs/wiremock/latest/wiremock/struct.Mock.html#method.expect) method.

From what I've seen it should be fairly easy to add support for the expect method by extending the json ([JsonStub](https://github.com/beltram/stubr/blob/4abb63f45a88e826efae7bd54c2f509a32b00c2d/lib/src/model/mod.rs#L15)) with an optional and stubr specific property that is then passed to the [MockBuilder](https://github.com/beltram/stubr/blob/4abb63f45a88e826efae7bd54c2f509a32b00c2d/lib/src/model/mod.rs#L30).

Does that sound like something you would be open to support? If yes I'd be happy to open a PR for it.

Thanks

**Comment by beltram** [comment]
Hey, thanks for the kind words. That would definitely be a nice addition. How I see things:

Unfortunately there's [no equivalent in Wiremock](https://wiremock.org/docs/verifying/)... not a problem 😄   

* Let's introduce an `expect: u32` field in JsonStub.
* Add a configuration option to [Config](https://docs.rs/stubr/latest/stubr/struct.Config.html) named `scoped` defaulting to false. I think this should be opted in because I doubt you'll ever want that on a standalone server, whereas you want this in a unit test
* Use [register_as_scoped](https://docs.rs/wiremock/latest/wiremock/struct.MockServer.html#method.register_as_scoped) instead of [register](https://docs.rs/wiremock/latest/wiremock/struct.MockServer.html#method.register) . This should return a `Vec<MockGuard>` you should store in [Stubr](https://docs.rs/stubr/latest/stubr/struct.Stubr.html) struct. Once it will be dropped, verifications will be made !

Sounds good to you ?

**Comment by geovie** [comment]
Overall it sounds good, but I'm not sure if scoped is the thing we want here I think adding a configuration option to enable the expect handling is what we want.

Because if I understand it correctly: with the "unscoped" version the mock server would panic if an expectation was not met.
So if `scoped` is `false` and we call `expect` is will also panic when the tests finishes.

So I'd propose: 😊 
- Let's introduce an expect: Option<u32> field in JsonStub.
- Add a configuration option to [Config](https://docs.rs/stubr/latest/stubr/struct.Config.html) named `verify`(?) defaulting to false.
- If the `verify` option is set and there is an `expect` in the json we set it in the [MockBuilder](https://github.com/beltram/stubr/blob/4abb63f45a88e826efae7bd54c2f509a32b00c2d/lib/src/model/mod.rs#L30)

**Comment by beltram** [comment]
> Because if I understand it correctly: with the "unscoped" version the mock server would panic if an expectation was not met.
So if scoped is false and we call expect is will also panic when the tests finishes.

Yes you're right. The "unscoped" version does the verifications when the server is shut down so it's the same.

> Let's introduce an expect: Option<u32> field in JsonStub.
    Add a configuration option to [Config](https://docs.rs/stubr/latest/stubr/struct.Config.html) named `verify_expect` defaulting to false.
    If the verify option is set and there is an expect in the json we set it in the [MockBuilder](https://github.com/beltram/stubr/blob/4abb63f45a88e826efae7bd54c2f509a32b00c2d/lib/src/model/mod.rs#L30)
    
  LGTM 😄
