### ISSUE TITLE
Performance comparison to Wiremock Java

### ISSUE THREAD

**Issue by DenialAdams** [beltram/stubr#6]
Hey! I know this project is in the earlier stages, but I am in love with it already. I currently use Java Wiremock and I'm often frustrated by its performance. I was wondering if integrating a benchmark might be possible, so that you could advertise any speed improvements or even just track progress in that area.

Cheers, and thanks for your work!

**Comment by beltram** [comment]
Hey !
Well thanks for the kind words.

There actually is a naive benchmark available [here](https://github.com/beltram/stubr/blob/main/bench/report.md). It is very simple, no optimizations at all. It looks already promising
* better, steadier throughput
* 25% of cpu usage required by Wiremock
* 0.2% -> 2% of memory required by Wiremock

It used to be in root README, I'll rollback this.  

I also plan using [criterion](https://crates.io/crates/criterion) in order to track progress.

**Comment by DenialAdams** [comment]
> 
> 
> Hey !
> Well thanks for the kind words.
> 
> There actually is a naive benchmark available [here](https://github.com/beltram/stubr/blob/main/bench/report.md). It is very simple, no optimizations at all. It looks already promising
> 
>     * better, steadier throughput
> 
>     * 25% of cpu usage required by Wiremock
> 
>     * 0.2% -> 2% of memory required by Wiremock
> 
> 
> It used to be in root README, I'll rollback this.
> 
> I also plan using [criterion](https://crates.io/crates/criterion) in order to track progress.

Thank you for the information!! That benchmark is super great to see :)

**Comment by beltram** [comment]
Hi again,
I've just publised some other benchmarks using [criterion](https://crates.io/crates/criterion). They bench core features and aim at tracking progresses. They'll be in each release assets.  
I've yet to figure out how to display them in a nicer way ; especially being able to quickly spot differences between 2 versions.  
You can find download instructions [here](https://github.com/beltram/stubr#cargo-bench).  
Cheers !
